# Supervised learning practice

- Objective: Explore some supervisal learning algorithms in missiles dataset
### Question 1

1. When doing supervised learning, what are the main preparation steps of our dataset?

In [1]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [3]:
## Load dataset

df =pd.read_csv("dataset_practical_session.csv")

In [3]:
x = df.drop("PK",axis=1)
y = df["PK"]

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

**Response**:
The main preparation are clean, normalize and separate data into target or label and features data. 

---

### Question 2

2. Supervised learning is about minimizing a loss. What is the loss we are going to minimize? 

**Response**

The loss we talk about is the distance between each points and the curve that we can create to do prediction on all the dataset

---

### Question 3

3. s this loss the only indicator of a good regression? Which other metrics could be relevant to look at? 

**Response**
No, we can have a loss near to zero but in the most of cases is caused by an overfitted function  so is good to see another metrics like precision, accuracy, etc

---

### Question 4

4. For each of the following regression method, report the metrics once the loss minimization has be done. Report also the size of the model in memory, as well as the inference time (the time it takes to output the PK given a configuration never seen in the dataset).

#### 4.1 
- Test linear regression. Ridge regression. Lasso regression.

In [6]:
## import models
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error

##### Linear regression

- time taken to do prediction 0.0754258390000011
- MAE: 0.24017291881641117
- MSE: 0.0795356268557765

In [7]:
regr = LinearRegression()
regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

0.9535942755001849

In [8]:
import sys

print(f"The model size is {sys.getsizeof(regr)/1024} kbytes")

The model size is 0.046875 kbytes

In [10]:
from time import process_time

start = process_time()
y_pred = regr.predict(X_test)        # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.0034802099999993175
MAE: 3.7865086220070387
MSE: 20.610854595616964

##### Ridge

- time taken to do prediction 0.018249379000000232
- MAE: 0.24017285585050893
- MSE: 0.07953562714604658

In [11]:
from sklearn.linear_model import Ridge

In [12]:
regr = Ridge()
regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

0.953584462851816

In [13]:
import sys

print(f"The model size is {sys.getsizeof(regr)} bytes")

The model size is 48 bytes

In [15]:
from time import process_time

start = process_time()
y_pred = regr.predict(X_test)        # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.004117807000000084
MAE: 3.787168574959558
MSE: 20.615212830962086

##### Lasso


- time taken to do prediction 0.04633431900000318
- MAE: 0.28142792417158485
- MSE: 0.12116216543065043

In [16]:
from sklearn.linear_model import Lasso

In [17]:
regr = Lasso()
regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

0.9355349636081821

In [18]:
import sys

print(f"The model size is {sys.getsizeof(x)/1024/1024} Mbytes")

The model size is 0.1069488525390625 Mbytes

In [19]:
from time import process_time

start = process_time()
y_pred = regr.predict(X_test)        # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.0033251269999965416
MAE: 4.468983464876887
MSE: 28.631801483418513

#### 4.2
- Test polynomial regression. With Ridge regularizer. With Lasso regularizer.

##### Polynomial 

- time taken to do prediction 0.31794890100000117
- MAE: 0.17561052100007568
- MSE: 0.0495701048963892

In [20]:
from sklearn.preprocessing import PolynomialFeatures

In [21]:
pr = PolynomialFeatures(degree = 3)
X_poly = pr.fit_transform(X_train)
lr_2 = LinearRegression()
lr_2.fit(X_poly, y_train)

LinearRegression()

In [22]:
import sys

print(f"The model size is {sys.getsizeof(lr_2)} bytes")

The model size is 48 bytes

In [23]:
from time import process_time

start = process_time()
y_pred = lr_2.predict(pr.fit_transform(X_test))       # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.010206367999998633
MAE: 0.01181393274922281
MSE: 0.000226541339340057

##### Polynomial Ridge

- time taken to do prediction 0.27823177799999854
- MAE: 0.17561038782503954
- MSE: 0.04957013643038816

In [24]:
pr = PolynomialFeatures(degree = 3)
X_poly = pr.fit_transform(X_train)
lr_2 = Ridge()
lr_2.fit(X_poly, y_train)

Ridge()

In [25]:
import sys

print(f"The model size is {sys.getsizeof(lr_2)} bytes")

The model size is 48 bytes

In [26]:
from time import process_time

start = process_time()
y_pred = lr_2.predict(pr.fit_transform(X_test))       # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.016404346999998154
MAE: 0.1106990873292263
MSE: 0.022215246177854996

##### Polynomial Lasso

- time taken to do prediction 0.5439367559999937
- MAE: 0.20374029466135135
- MSE: 0.06540468526985661

In [27]:
pr = PolynomialFeatures(degree = 3)
X_poly = pr.fit_transform(X_train)
lr_2 = Lasso()
lr_2.fit(X_poly, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.663e+04, tolerance: 8.768e+01
  model = cd_fast.enet_coordinate_descent(

Lasso()

In [28]:
import sys

print(f"The model size is {sys.getsizeof(lr_2)} bytes")

The model size is 48 bytes

In [29]:
from time import process_time

start = process_time()
y_pred = lr_2.predict(pr.fit_transform(X_test))       # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.03057773100000105
MAE: 1.709578991326705
MSE: 6.156613710748349

#### 4.3 

- Test Decision tree regression. Test Random Forest regression.

##### Decision tree

- time taken to do prediction 0.03881889100000535
- MAE: 0.019802433149003245
- MSE: 0.006677680818224816

In [30]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [31]:
tree = DecisionTreeRegressor(random_state=42)

param_grid_tree = {
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

grid_tree = GridSearchCV(tree, param_grid_tree, cv=3, scoring="neg_mean_squared_error", n_jobs=-1)
grid_tree.fit(X_train, y_train)

print("Best params (DecisionTree, GridSearch):", grid_tree.best_params_)
print("MSE (DecisionTree):", mean_squared_error(y_test, grid_tree.best_estimator_.predict(X_test)))

Best params (DecisionTree, GridSearch): {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
MSE (DecisionTree): 1.6009917961478664

In [ ]:
import sys

print(f"The model size is {sys.getsizeof(grid_tree.best_params_)} bytes")

The model size is 232 bytes

In [32]:
from time import process_time

start = process_time()
y_pred =  grid_tree.best_estimator_.predict(X_test)      # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.0038477410000012924
MAE: 1.1624779661914642
MSE: 1.6009917961478664

In [33]:
# 3. RandomSearch para DecisionTree
# ==============================
from scipy.stats import randint

param_dist_tree = {
    "max_depth": [None] + list(range(3, 30)),
    "min_samples_split": randint(2, 20),
    "min_samples_leaf": randint(1, 20)
}

rand_tree = RandomizedSearchCV(tree, param_dist_tree, n_iter=20, cv=3,
                               scoring="neg_mean_squared_error", n_jobs=-1, random_state=42)
rand_tree.fit(X_train, y_train)

print("Best params (DecisionTree, RandomSearch):", rand_tree.best_params_)
print("MSE (DecisionTree, RandomSearch):", mean_squared_error(y_test, rand_tree.best_estimator_.predict(X_test)))

Best params (DecisionTree, RandomSearch): {'max_depth': 25, 'min_samples_leaf': 3, 'min_samples_split': 3}
MSE (DecisionTree, RandomSearch): 3.1327948145968043

In [34]:
from time import process_time

start = process_time()
y_pred =  rand_tree.best_estimator_.predict(X_test)      # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True

print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.003730982999996968
MAE: 1.573357122208655
MSE: 3.1327948145968043

##### RandomForest

- time taken to do prediction 0.1864740849999862
- MAE: 0.01549911470239555
- MSE: 0.00457507695601936

In [36]:
from sklearn.ensemble import RandomForestRegressor

In [37]:
forest = RandomForestRegressor(random_state=42)

In [38]:
param_grid_forest = {
    "n_estimators": [2, 5],
    "max_depth": [None, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

grid_forest = GridSearchCV(forest, param_grid_forest, cv=3, scoring="neg_mean_squared_error", n_jobs=-1)
grid_forest.fit(X_train, y_train)

print("Best params (RandomForest, GridSearch):", grid_forest.best_params_)
print("MSE (RandomForest, GridSearch):", mean_squared_error(y_test, grid_forest.best_estimator_.predict(X_test)))

Best params (RandomForest, GridSearch): {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 5}
MSE (RandomForest, GridSearch): 1.2111156088005637

In [39]:
from time import process_time

start = process_time()
y_pred =  grid_forest.best_estimator_.predict(X_test)     # Time measuring
end = process_time()

print(f"time taken to do prediction {end - start}")


mae = mean_absolute_error(y_true=y_test,y_pred=y_pred)
#squared True returns MSE value, False returns RMSE value.
mse = mean_squared_error(y_true=y_test,y_pred=y_pred) #default=True


print("MAE:",mae)
print("MSE:",mse)

time taken to do prediction 0.01028330900000185
MAE: 0.9305655697059446
MSE: 1.2111156088005637

In [40]:


param_dist_forest = {
    "n_estimators": randint(2, 10),
    "max_depth": [None] + list(range(5, 30)),
    "min_samples_split": randint(2, 20),
    "min_samples_leaf": randint(1, 20),
    "max_features": ["auto", "sqrt", "log2"]
}

rand_forest = RandomizedSearchCV(forest, param_dist_forest, n_iter=20, cv=3,
                                 scoring="neg_mean_squared_error", n_jobs=-1, random_state=42)
rand_forest.fit(X_train, y_train)

print("Best params (RandomForest, RandomSearch):", rand_forest.best_params_)
print("MSE (RandomForest, RandomSearch):", mean_squared_error(y_test, rand_forest.best_estimator_.predict(X_test)))

Best params (RandomForest, RandomSearch): {'max_depth': 13, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 15, 'n_estimators': 8}
MSE (RandomForest, RandomSearch): 8.729196893801838

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:542: FitFailedWarning:
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 890, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:1051: UserWarning: One or more of the test scores are non-finite: [         nan -53.79926101          nan -22.95185515 -19.83698148
          nan -24.5411196           nan          nan          nan
 -18.03050505          nan          nan -20.42119417          nan
 -12.57804453 -15.15721288 -17.23834547 -22.40069455          nan]
  warnings.warn(

# Less dimension

Definition of k

In [2]:
import pandas as pd
import numpy as np
from scipy.optimize import curve_fit

df = pd.read_csv("dataset_practical_session.csv")
y=df["PK"]
X=df.drop("PK", axis=1)

In [3]:
def sigmoid(d, d0,k):
    return 1/(1+np.exp(k*(d-d0)))

df_final=pd.DataFrame(columns=["MACH_BLUE", "MACH_RED", "ALT_BLUE", "ALT_RED", "DELTA", "D0", "K"])

new_rows=[]

for x1 in set(df["MACH_BLUE"]):
    for x2 in set(df["MACH_RED"]):
        for x3 in set(df["ALT_BLUE"]):
            for x4 in set(df["ALT_RED"]):
                for x5 in set(df["DELTA"]):
                    mask=(
                        (df["MACH_BLUE"]==x1)&(df["MACH_RED"]==x2)&
                        (df["ALT_BLUE"]==x3)&(df["ALT_RED"]==x4)&
                        (df["DELTA"]==x5)
                    )
                    X_f=X[mask]
                    y_f=y[mask]
                    d_values=X_f["DISTANCE"].values
                    y_values=y_f.values

                    popt, _ = curve_fit(sigmoid, d_values, y_values, [np.median(d_values), 0])

                    d0, k = popt
                    new_rows.append({"MACH_BLUE": x1, "MACH_RED": x2, "ALT_BLUE": x3, "ALT_RED": x4, "DELTA": x5, "D0":d0, "K":k})

df_final=pd.DataFrame(new_rows)
df_final

      MACH_BLUE  MACH_RED  ALT_BLUE  ALT_RED  DELTA         D0         K
0           0.5       0.5         0        0    0.0  15.914397  1.500106
1           0.5       0.5         0        0    0.5  18.076019  1.517197
2           0.5       0.5         0        0    2.0  39.931532  1.499416
3           0.5       0.5         0        0    1.0  22.813075  1.520306
4           0.5       0.5         0        0    1.5  30.083134  1.504848
...         ...       ...       ...      ...    ...        ...       ...
2795        1.5       1.5        30       30    2.0  50.943594  1.497461
2796        1.5       1.5        30       30    1.0  33.546440  1.510358
2797        1.5       1.5        30       30    1.5  40.948936  1.527054
2798        1.5       1.5        30       30    2.5  63.571165  1.485787
2799        1.5       1.5        30       30    3.0  78.799949  1.521374

[2800 rows x 7 columns]

In [4]:

df_final.describe()

,MACH_BLUE,MACH_RED,ALT_BLUE,ALT_RED,DELTA,D0,K
count,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000,2800.000000
mean,1.250000,1.250000,20.000000,20.000000,1.500000,43.200885,1.498416
std,0.559117,0.559117,14.144662,14.144662,1.000179,20.599332,0.032806
min,0.500000,0.500000,0.000000,0.000000,0.000000,1.869842,1.102040
25%,0.875000,0.875000,10.000000,10.000000,0.500000,27.357377,1.480296
50%,1.250000,1.250000,20.000000,20.000000,1.500000,39.842304,1.499307
75%,1.625000,1.625000,30.000000,30.000000,2.500000,57.742732,1.518190
max,2.000000,2.000000,40.000000,40.000000,3.000000,99.586389,1.614540

In [5]:
# Reuse all function
y=df_final["D0"]
x=df_final.drop(["D0", "K"], axis=1)

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)